### PR TITLE
developers(Conventions): Conventions Update, 201905

### PR DESCRIPTION
**Pull request by thomashermine**
At the light of our recents work/briefing/debriefing during _DX on Sterroids_ #6 and _The Great Migration_ #3 , I suggest a few editions of our Conventions.

Commits titles are self-explanatory, please read them below for a list of suggested changes

### CODE REVIEW

**Comment by thomashermine** [comment]
@denisflorkin I agree with your analysis, and pros/cons given.
But I see a few more Pros for Flow:

- Allows typing of anything, not only Props (functions) 
- Check at compile time (>< Runtime), **allows better IDE integration** (autocompletion, warning-as-you-type) <-- this is the killer reason for me, having used both

Also, this is totally subjective (that's why I don't put this in the list), but I feel like Flow is more "future-proof" and the React community is moving away from PropTypes towards Flow.


 A few (biased!) links:
- https://stackoverflow.com/questions/36065185/react-proptypes-vs-flow
https://medium.com/@linmic/its-time-to-remove-proptypes-and-just-use-flow-for-react-4a3de615aac5
- http://blog.rstankov.com/flow-as-replacement-for-proptype/

**Comment by thomashermine** [comment]
@ferrarisMat @geecko86 @antony-funquality @utilisatrice42 

This would be sad if this become only a matter of "Denis VS Thomas" (shall we rent [Le Palais 12](https://www.rtbf.be/info/medias/detail_booba-annonce-que-son-combat-contre-kaaris-aura-lieu-a-bruxelles-au-palais-12?id=10115522) ? 🤣

Please, make your voices heard in this choice :) 

I don't have any really strong opinion towards any option, and could live with both :-)

**Comment by antony-funquality** [comment]
Not tested flow (I do not have the time to check this now).
Do not like PropTypes as it does only some vague warnings.

In all cases, not really convinced about this kind of stuff, seems really a lost of time from my point of view.

**Comment by thomashermine** [comment]
@ferrarisMat @geecko86 @utilisatrice42 Up, still waiting for your opinions

**Comment by utilisatrice42** [comment]
I not really have an opinion, I'm learning a lot and I'm a little lost. I don't really have a lot of experiences with Storybook or Flow.

**Comment by thomashermine** [comment]
Questions/remarks from @denisflorkin on Slack : 

> I am not against flow, as long as it is possible to "just not type" things without it being an "flow error"
> 
> some more complex data structure might/will take days to type/decribe...
> 
> also need to investigate adding it to CRA, looks like they integrate well with the flow cli, but need to see if typings are stripped on build...

**Comment by thomashermine** [comment]
> I am not against flow, as long as it is possible to "just not type" things without it being an "flow error"

Rest assured, It's clearly not the case, Flow is really designed to be incrementally adopted

> You can also adopt Flow incrementally and easily remove it at anytime, so you can try Flow out on any codebase and see how you like it.
> (Source)[https://flow.org/en/docs/getting-started/]

**Comment by geecko86** [comment]
There seems to be some very interesting examples of cases where GraphQL, mongoose and flow are being used together. I hope I don't regret this later on but yeah sounds good to me!

**Comment by antony-funquality** [comment]
Is there a way to easily "encode" the flow configuration object?
Like @denisflorkin, on my other project, I have already been concerned about complex nested object description (with props, but the idea is the same) and finally decided to throw everything out to avoid loosing time describing my things.

**Comment by thomashermine** [comment]
As discussed during Weekly Brief, we will do a test run of Flow, and thus I'm enforcing theses new conventions

**Pull request merged**
