### PR TITLE
Add section on feminism

### PR DESCRIPTION
**Pull request by geecko86**
Credit goes to @utilisatrice42 and myself. :)

### CODE REVIEW

**Comment by thomashermine** [comment]
What do you guys think about placement? Is this at the right place now?

**Comment by thomashermine** [comment]
A suggestion from @ys, on Twitter:

https://twitter.com/yann_ck/status/1133754266433277953

WDYT?

**Comment by mathieudelvaux** [comment]
I am all for minorities being represented more in our DNA. I don't really know how to tackle the issue, but @ys seems like he may have an idea :)

About placement, I would place it right after "Come as you are", since it would be a good starting point for feminism, diversity and equality in general

**Comment by utilisatrice42** [comment]
I think the placement after "Come as you are" is not convenient, "Come as you are" talk about clothes... 

Maybe can we write a new "chapter" about inclusivity in general where the subtitle feminisme can be include. However, I'm not confortable about speaking/writing for other minorities but I can do some research :)

**Pull request merged**
